import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import test from "node:test";
import { calculatePdfRenderDpi } from "../lib/pdf-processing.mjs";
import { adjustOriginForCrop } from "../lib/preprocessing.mjs";

function sourceSection(source, startMarker, endMarker) {
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker, start + startMarker.length);
  assert.notEqual(start, -1, `Missing source marker: ${startMarker}`);
  assert.notEqual(end, -1, `Missing source marker: ${endMarker}`);
  return source.slice(start, end);
}

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the MapForge application", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>MapForge ROS \| PGM \+ YAML Generator<\/title>/i);
  assert.match(html, /Turn a floor plan into a/);
  assert.match(html, /Complete both confirmations to export/);
  assert.match(html, /PDF \/ PNG \/ JPG \/ JPEG/);
  assert.match(html, /PNG \/ JPG \/ JPEG/);
  assert.match(html, /White \/ free cutoff/);
  assert.match(html, /crop and clean drafting artifacts/i);
  assert.match(html, /Full-sheet map origin/i);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape/i);
});

test("keeps ROS-compatible defaults and exact reviewed trinary export", async () => {
  const [
    page,
    editor,
    layout,
    packageJson,
    socialImage,
    pdfWorker,
    trinary,
  ] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/CleanupEditor.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    stat(new URL("../public/og.png", import.meta.url)),
    stat(new URL("../public/pdf.worker.min.mjs", import.meta.url)),
    readFile(new URL("../lib/trinary-occupancy.mjs", import.meta.url), "utf8"),
  ]);

  assert.match(page, /resolution: "0\.05"/);
  assert.match(page, /originX: "0\.0"/);
  assert.match(page, /originY: "0\.0"/);
  assert.match(page, /originYaw: "0\.0"/);
  assert.match(page, /mode: "trinary"/);
  assert.match(page, /occupiedThreshold: "0\.65"/);
  assert.match(page, /freeThreshold: "0\.25"/);
  assert.match(page, /whiteCutoff: "255"/);
  assert.match(page, /`P5\\n# Generated by MapForge ROS\\n/);
  assert.match(page, /image: \$\{pgmName\}/);
  assert.match(page, /new Blob\(\[pgmBuffer\]/);
  assert.match(page, /image\/x-portable-graymap/);
  assert.match(page, /classifyExteriorUnknown\(/);
  assert.match(page, /const outputPixels = finalSnapshot\.pixels/);
  assert.match(page, /pgmBytes\.set\(outputPixels, header\.length\)/);
  assert.doesNotMatch(page, /processedMap\?\.pixels/);
  assert.match(page, /finalSnapshot\.revision !== mapRevisionRef\.current/);
  assert.match(page, /confirmedMapRevision !== finalSnapshot\.revision/);
  assert.match(page, /mode: trinary/);
  assert.match(page, /negate: 0/);
  assert.match(trinary, /TRINARY_OCCUPIED = 0/);
  assert.match(trinary, /TRINARY_UNKNOWN = 127/);
  assert.match(trinary, /TRINARY_FREE = 255/);
  assert.match(page, /<CleanupEditor/);
  assert.match(page, /application\/pdf/);
  assert.match(page, /import\("pdfjs-dist"\)/);
  assert.match(page, /PDF page \$\{pageNumber\} of/);
  assert.match(page, /pdfLoadingTaskRef/);
  assert.match(page, /pdfRenderTaskRef/);
  assert.match(page, /workerSrc = "\/pdf\.worker\.min\.mjs"/);
  assert.match(page, /resolution: DEFAULTS\.resolution/);
  assert.match(page, /Wait for the selected floor-plan page to finish rendering/);
  assert.match(page, /disabled=\{isLoadingFile\}/);
  assert.match(page, /resolutionLocked=\{Boolean\(pdfMeta\)\}/);
  assert.match(editor, /disabled=\{resolutionLocked\}/);
  for (const [startMarker, endMarker] of [
    ["<span>Map mode</span>", "<span>Negate</span>"],
    ["<span>Negate</span>", "<span>White / free cutoff</span>"],
    ["<span>Occupied threshold</span>", "<span>Free threshold</span>"],
  ]) {
    assert.match(sourceSection(page, startMarker, endMarker), /disabled/);
  }
  assert.match(editor, /Scan and preview/);
  assert.match(editor, /Apply red removals/);
  assert.match(editor, /Reachability start/);
  assert.match(editor, /Scale endpoints/);
  assert.match(editor, /isMaskPixelSet\(suggestion, sourceIndex\)/);
  assert.doesNotMatch(editor, /suggestion\?\.\[sourceIndex\] !== 0/);
  assert.match(layout, /new URL\("\/og\.png", baseUrl\)/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  assert.match(packageJson, /"pdfjs-dist": "6\.2\.108"/);
  assert.match(packageJson, /tests\/\*\.test\.mjs/);
  assert.ok(socialImage.size > 100_000);
  assert.ok(pdfWorker.size > 1_000_000);
});

test("ties PDF scale confirmation to the successfully rendered raster", async () => {
  const [page, pdfProcessing] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../lib/pdf-processing.mjs", import.meta.url), "utf8"),
  ]);

  assert.match(
    pdfProcessing,
    /PDF_SUPPORTED_SCALE_DENOMINATORS = Object\.freeze\(\[250, 400\]\)/,
  );
  assert.match(pdfProcessing, /PDF_DESIRED_RESOLUTION = 0\.05/);
  assert.match(pdfProcessing, /PDF_MAX_PIXELS = 25_000_000/);
  assert.match(pdfProcessing, /PDF_MAX_DIMENSION = 6_500/);
  assert.match(
    pdfProcessing,
    /\(\(scaleDenominator \* 0\.0254\) \/ resolution\)/,
  );
  assert.match(pdfProcessing, /throw new PdfRenderLimitError\(/);

  assert.match(page, /PDF_SUPPORTED_SCALE_DENOMINATORS\.map/);
  assert.match(page, /calculatePdfRenderPlan\(/);
  assert.match(page, /scaleDenominator: requestedScaleDenominator/);
  assert.match(page, /resolution: PDF_DESIRED_RESOLUTION/);
  assert.match(page, /scaleSelectionMatchesRaster/);
  assert.match(page, /confirmedScaleRevision === imageMeta\.revision/);
  assert.match(page, /I checked the title block and confirm this PDF is 1:/);
  assert.equal(calculatePdfRenderDpi(250, 0.05), 127);
  assert.equal(calculatePdfRenderDpi(400, 0.05), 203.2);
  assert.match(
    page,
    /PDF maps are locked to the required 0\.05 m\/pixel; the selected printed scale controls DPI/,
  );
});

test("invalidates stale review and download state on export-relevant changes", async () => {
  const page = await readFile(
    new URL("../app/page.tsx", import.meta.url),
    "utf8",
  );

  const updateSetting = sourceSection(
    page,
    "const updateSetting =",
    "const handleCleanupResult =",
  );
  const cleanupResult = sourceSection(
    page,
    "const handleCleanupResult =",
    "const handleCalibratedResolution =",
  );
  const loadPdf = sourceSection(page, "const loadPdf =", "const loadImage =");
  const loadImage = sourceSection(page, "const loadImage =", "const loadFile =");
  const selectScale = sourceSection(
    page,
    "const selectPrintedScale =",
    "const handleFileInput =",
  );

  for (const section of [updateSetting, cleanupResult, loadPdf, loadImage, selectScale]) {
    assert.match(section, /invalidateMapReview\(\)/);
    assert.match(section, /releaseGeneratedFiles\(\)/);
  }

  assert.match(page, /mapRevisionRef\.current \+= 1/);
  assert.match(page, /setConfirmedMapRevision\(null\)/);
  assert.match(page, /URL\.revokeObjectURL\(files\.pgmUrl\)/);
  assert.match(page, /URL\.revokeObjectURL\(files\.yamlUrl\)/);
  assert.match(page, /requestedRevision !== mapRevisionRef\.current/);
  assert.match(page, /processedMapRef\.current !== processedMap/);
  assert.match(page, /disabled=\{!reviewReadyForExport\}/);
});

test("converts a top-left source crop into a yaw-aware ROS origin", async () => {
  const page = await readFile(
    new URL("../app/page.tsx", import.meta.url),
    "utf8",
  );

  assert.match(
    page,
    /finalSnapshot\.crop\.left,\s*imageMeta\.height - finalSnapshot\.crop\.bottom,\s*resolution/s,
  );
  assert.match(
    page,
    /origin: \[\$\{yamlNumber\(adjustedOrigin\.x\)\}, \$\{yamlNumber\(adjustedOrigin\.y\)\}/,
  );

  const sourceHeight = 80;
  const crop = { left: 10, top: 5, right: 90, bottom: 60 };
  const bottomPixels = sourceHeight - crop.bottom;
  assert.deepEqual(
    adjustOriginForCrop(1, 2, 0, crop.left, bottomPixels, 0.05),
    { x: 1.5, y: 3 },
  );

  const rotated = adjustOriginForCrop(
    1,
    2,
    Math.PI / 2,
    crop.left,
    bottomPixels,
    0.05,
  );
  assert.ok(Math.abs(rotated.x) < 1e-12);
  assert.ok(Math.abs(rotated.y - 2.5) < 1e-12);

  // Removing pixels only from the source top does not move the ROS lower-left.
  assert.deepEqual(adjustOriginForCrop(1, 2, 0, 0, 80 - 80, 0.05), {
    x: 1,
    y: 2,
  });
});

test("includes reversible shape editing and large-map viewport controls", async () => {
  const editor = await readFile(
    new URL("../app/CleanupEditor.tsx", import.meta.url),
    "utf8",
  );

  // Every committed patch retains both directions, and committing a new edit
  // invalidates the redo branch.
  assert.match(editor, /const redoRef = useRef<HistoryPatch\[\]>/);
  assert.match(editor, /applyPixelPatch\(pixels, patch, "undo"\)/);
  assert.match(editor, /applyPixelPatch\(pixels, patch, "redo"\)/);
  assert.match(editor, /redoRef\.current = \[\]/);
  assert.match(editor, /Undo\{undoCount/);
  assert.match(editor, /Redo\{redoCount/);
  assert.match(
    editor,
    /event\.ctrlKey\s*\|\|\s*event\.metaKey|event\.metaKey\s*\|\|\s*event\.ctrlKey/,
  );
  assert.match(editor, /key === "z"/);
  assert.match(editor, /key === "y"/);
  assert.match(editor, /event\.shiftKey/);

  // Shape previews use a separate canvas and rasterize only when committed.
  for (const [shape, label] of [
    ["freehand", "Brush"],
    ["line", "Line"],
    ["rectangle", "Rectangle"],
    ["filledRectangle", "Filled rectangle"],
  ]) {
    assert.match(editor, new RegExp(`\\["${shape}", "${label}"\\]`));
  }
  assert.match(editor, /rasterizeThickLine\(/);
  assert.match(editor, /rasterizeRectangle\(/);
  assert.match(editor, /previewCanvasRef/);
  assert.match(editor, /shapePreview/);
  assert.match(editor, /rgba\(/);
  assert.match(editor, /onPointerCancel=\{handlePointerCancel\}/);
  assert.match(editor, /Pending map edit cancelled without changing the saved map/);
  assert.match(editor, /pixels:\s*pixels\.slice\(\)/);

  // Navigation is view-only and uses source-aware coordinate/zoom helpers.
  assert.match(editor, />\s*Pan\s*</);
  assert.match(editor, />\s*Fit\s*</);
  assert.match(editor, /spaceHeldRef/);
  assert.match(editor, /clientPointToSource\(/);
  assert.match(editor, /fitZoomPercent\(/);
  assert.match(editor, /zoomAnchorScrollDelta\(/);
  assert.match(editor, /addEventListener\("wheel", handleWheel, \{ passive: false \}\)/);
  assert.match(editor, /onKeyDown=\{handleStageKeyDown\}/);
  assert.match(editor, /event\.key === "Escape"/);
});

test("includes explicit validation for missing files and invalid resolution", async () => {
  const page = await readFile(
    new URL("../app/page.tsx", import.meta.url),
    "utf8",
  );

  assert.match(page, /Upload a floor plan before generating files\./);
  assert.match(page, /Resolution must be a number greater than zero\./);
  assert.match(page, /freeThreshold >= occupiedThreshold/);
  assert.match(page, /Choose a PDF, PNG, JPG, or JPEG floor plan\./);
  assert.match(page, /White cutoff must be a whole number from 1 to 255\./);
});
